# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='munchuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='munchuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='last name'),
        ),
    ]
